### ISSUE TITLE
Great Idea for  MusicPiped Web. 

### ISSUE THREAD

**Issue by HarryHeights** [deep-gaurav/musicpiped_web#1]
When should I expect a workable product?

**Comment by deep-gaurav** [comment]
It's working..
link is given in readme
I recommend chrome since some API used aren't implemented in other browsers like notification control APIs.

https://deep-gaurav.github.io

**Comment by HarryHeights** [comment]
Tried it.. Using it right now. Thanks

**Comment by deep-gaurav** [comment]
Great, feedback will be appreciated :) 
closing issue
